version: '3'
services:
   
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki/
      - ./.config/loki.yaml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    user: "0:0"  # Run as root to avoid permission issues
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./.config/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/tmp/tempo

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana/
      - ./.config/grafana/datasources:/etc/grafana/provisioning/datasources 
      - ./.config/grafana/dashboards:/var/lib/grafana/dashboards
      - ./.config/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
    environment:
       - GF_AUTH_ANONYMOUS_ENABLED=true
       - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
    ports:
      - "3000:3000"
  
  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./.config/config.alloy:/etc/alloy/config.alloy
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    ports:
      - "12345:12345"
      - "4317:4317"

  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    ports:
      - "9009:9009" # Query API
    volumes:
      - ./.config/mimir.yaml:/etc/mimir/mimir.yaml
    command:
      - --config.file=/etc/mimir/mimir.yaml

  # node-exporter:
  #   image: prom/node-exporter:latest
  #   container_name: node-exporter
  #   restart: always
  #   network_mode: "host" # Use host network to access system metrics
  #   ports:
  #     - "9100:9100" # Node Exporter listens on this port by default
  #   volumes:
  #     - ./tmp/proc:/host/proc:ro
  #     - ./tmp/sys:/host/sys:ro
  #     - ./tmp/:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.sysfs=/host/sys'
  #     - '--path.rootfs=/rootfs'

  # blackbox-exporter:
  #   image: prom/blackbox-exporter:latest
  #   container_name: blackbox-exporter
  #   restart: always
  #   ports:
  #     - "9115:9115" # Blackbox Exporter listens on this port by default
  #   volumes:
  #     - ./.config/blackbox.yml:/etc/blackbox_exporter/config.yml:ro
  #   command:
  #     - "--config.file=/etc/blackbox_exporter/config.yml"

volumes:
    grafana_data:
    loki_data:
    tempo_data:
