version: '3'
services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: openobserve
    environment:
      - ZO_ROOT_USER_EMAIL=admin@example.com       # Admin email
      - ZO_ROOT_USER_PASSWORD=Admin@123     # Admin password
      - ZO_S3_SERVER_URL=http://minio:9000
      - ZO_S3_ACCESS_KEY=6bVGhnX73QURPPX3CO8E
      - ZO_S3_SECRET_KEY=FjbfzOEMofeLRBJfDxT6i3wyeac3MCbqCda8IgqQ
      - ZO_S3_BUCKET_NAME=openobserve_data
      - ZO_S3_PROVIDER=minio
      - ZO_S3_REGION_NAME=asia
    ports:
      - "5080:5080"                               # HTTP port for OpenObserve web UI/API
    restart: always

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001" # MinIO console
    environment:
      MINIO_ROOT_USER: myrootuser
      MINIO_ROOT_PASSWORD: myrootpassword
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
  
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel.yaml" ]
    volumes:
      - ./.config/otel.yaml:/etc/otel.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver

volumes:
  openobserve_data:
  minio_data: