version: '3'
services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: openobserve
    environment:
      - ZO_ROOT_USER_EMAIL=admin@example.com       # Admin email
      - ZO_ROOT_USER_PASSWORD=Admin@123     # Admin password
      - ZO_DATA_DIR=/data                         # Data directory inside the container
    ports:
      - "5080:5080"                               # HTTP port for OpenObserve web UI/API
    volumes:
      - openobserve_data:/data                              # Bind mount for persistent data storage
    restart: always
 
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel.yaml" ]
    volumes:
      - ./.config/otel.yaml:/etc/otel.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
volumes:
  openobserve_data: