version: '3'
services:
   
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./tmp/loki:/loki/
      - ./.config/loki.yaml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./.config/tempo.yaml:/etc/tempo.yaml
      - ./tmp/tempo:/tmp/tempo

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"
  
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel.yaml" ]
    volumes:
      - ./.config/otel.yaml:/etc/otel.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver

  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    ports:
      - "9009:9009" # Query API
    volumes:
      - ./.config/mimir.yaml:/etc/mimir/mimir.yaml
    command:
      - --config.file=/etc/mimir/mimir.yaml