version: '3'

services:
  elasticsearch:
    image: elasticsearch:8.17.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      # - xpack.security.enabled=false # Disable security for simplicity
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=123456
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Set Java heap size
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: kibana:8.17.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # - XPACK_SECURITY_ENABLED=true
      # - ELASTICSEARCH_USERNAME=elastic
      # - ELASTICSEARCH_PASSWORD="123456"
    ports:
      - "5601:5601" # Kibana UI
    depends_on:
      - elasticsearch

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel.yaml" ]
    volumes:
      - ./.config/otel.yaml:/etc/otel.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
volumes:
  es_data: